import { Metadata, Viewport } from 'next';
import { PropsWithChildren } from 'react';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Roboto } from 'next/font/google';
import { Box, ThemeProvider } from '@mui/material';

import './globals.css';
import { theme } from '@/config/theme';
import { Header } from '@/components';

const roboto = Roboto({
   weight: ['300', '400', '500', '700'],
   subsets: ['latin'],
   display: 'swap',
   variable: '--font-roboto',
});

export const metadata: Metadata = {
   title: 'Carhive',
   description: 'Generated by create next app',
};

export const viewport: Viewport = {
   width: 'device-width',
   initialScale: 1,
};

export default function RootLayout({ children }: PropsWithChildren) {
   return (
      <html lang="en">
         <body className={`${roboto.variable} ${roboto.className}`}>
            <AppRouterCacheProvider>
               <ThemeProvider theme={theme}>
                  <Box>
                     <Header />
                     <Box flexDirection="row">{children}</Box>
                  </Box>
               </ThemeProvider>
            </AppRouterCacheProvider>
         </body>
      </html>
   );
}
