import { ThemeProvider } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import { Metadata, Viewport } from 'next';
import { Roboto } from 'next/font/google';
import { PropsWithChildren } from 'react';
import { Toaster } from 'react-hot-toast';

import { Header } from '@/components';
import { theme } from '@/config/theme';
import { AuthContextProvider } from '@/features/auth/context/auth-context';

import './globals.css';

const roboto = Roboto({
   weight: ['300', '400', '500', '700'],
   subsets: ['latin'],
   preload: true,
   display: 'swap',
   variable: '--font-roboto',
});

export const metadata: Metadata = {
   title: 'Carhive',
   description: 'Generated by create next app',
};

export const viewport: Viewport = {
   width: 'device-width',
   initialScale: 1,
};

export default function RootLayout({ children }: PropsWithChildren) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body className={`${roboto.variable} ${roboto.className}`}>
            <AppRouterCacheProvider>
               <ThemeProvider theme={theme}>
                  <Toaster />
                  <InitColorSchemeScript attribute="class" />
                  <AuthContextProvider>
                     <div className="flex min-h-screen flex-col">
                        <Header />
                        <div className="flex grow-1 flex-col">{children}</div>
                     </div>
                  </AuthContextProvider>
               </ThemeProvider>
            </AppRouterCacheProvider>
         </body>
      </html>
   );
}
