import '@radix-ui/themes/styles.css';
import { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

import { Header } from '@/components';
import { LayoutProps } from '@/types/next';

import './globals.css';
import Providers from './providers';

const inter = Inter({
   subsets: ['latin'],
   display: 'swap',
   variable: '--font-inter',
   preload: true,
});

export const metadata: Metadata = {
   title: 'Carhive',
   description: 'Generated by create next app',
};

export const viewport: Viewport = {
   width: 'device-width',
   initialScale: 1,
};

export default function RootLayout({ children }: LayoutProps) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body className={`${inter.variable} ${inter.className}`}>
            <Providers>
               <div className="flex min-h-screen flex-col">
                  <Toaster />
                  <Header />
                  <main className="flex flex-1 flex-col px-10">{children}</main>
               </div>
            </Providers>
         </body>
      </html>
   );
}
